### ISSUE TITLE
Use environment variables in `config.json`

### ISSUE THREAD

**Issue by amirbtb** [anovis/goblet#100]
Hello

I start to have a lot of environment variables hard-coded in the `config.json` ; some are more sensitive than the others 🔒 . Would it be possible to allow the use of environment variable, and interpolate on run time, like the `GIT_TOKEN` and `EXAMPLE_ENV_VAR` here :
```
{
    "cloudfunction": {
        "runtime":"python37",
        "environmentVariables": {
            "KEY":"$EXAMPLE_ENV_VAR"
        },
        "buildEnvironmentVariables": {
            "GIT_TOKEN":"$GIT_TOKEN"
        },
        "availableMemoryMb": 256,
        "timeout": "30s"
    }
}
```

This could be particularly useful for local development, CI/CD and a light solution while waiting for the powerful [[Secret Manager] Secret Manager Integration #58](https://github.com/anovis/goblet/issues/58).

**Comment by anovis** [comment]
Thats a great question. We actually were running into something similar. 

so for running locally, goblet doesn't actually use the `config.json` so you can export and use the env variables regularly. 

for CI/CD we built in the functionality in a github action , where you can set the env vars using github secrets, and they will either override, or update the `config.json` variables. currently it just supports `environmentVariables` but can certainly add `buildEnvironmentVariables` as well

```
    - name: goblet deploy
      uses: anovis/goblet-github-actions@v2.3
      with:
        project: ${{ env.GCLOUD_PROJECT }}
        location: us-central1
        goblet-path: test
        stage: dev
        envars:  |-
          SLACK_WEBHOOK:${secrets.slack_secret},BILLING_ORG:bill,BILLING_ID:bill_id
```

behind the scenes it uses the goblet deploy cli option `@click.option('--config-from-json-string', 'config')`
which takes in a json string and updates the config based on that so you can inject secure variables during deploy time .

let me know if this makes sense
